# Generated by Django 5.1.5 on 2025-01-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
